---
# tasks file for iac-ansible-globodns
- name: Instalando Dependencias
  register: dep_installed
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
          - apache2
          - bind9
          - bind9utils
          - build-essential
          - bundler
          - g++
          - gcc
          - git
          - gnupg2
          - mariadb-devel 
          - mariadb-server
          - openssh-client
          - openssh-server
          - openssl
          - rsync
          - ruby
          - rubygems
          - sudo
...
