---
# tasks file for iac-ansible-globodns
- yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
        register: epel_installed

- yum: name={{ item }} state=latest
  when: epel_installed|success
  register: dep_installed
  with_items:
          - git
          - openssl
          - openssl-devel
          - openssh
          - openssh-server
          - openssh-clients
          - rsync
          - mariadb-server
          - mariadb-devel 
          - bind
          - bind-chroot
          - bind-utils
          - ruby
          - rubygems
          - httpd
          - sudo
          - gcc
          - gcc-c++
          - gnupg2
...
