---
# tasks file for iac-ansible-globodns
- name: Instalando Dependencias
  register: dep_installed
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
          - git
          - openssl
          - openssh-server
          - openssh-client
          - rsync
          - mariadb-server
          - mariadb-devel 
          - bind9
          - bind9utils
          - ruby
          - rubygems
          - apache2
          - sudo
          - gcc
          - g++
          - gnupg2
...
