---
# tasks file for globodns
- yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
        register: epel_installed

- yum: name={{ globodns_packages }} state=latest
  when: epel_installed|success
  register: dep_installed
