---
# tasks file for globodns
- name: Clone GloboDNS repo
  git:
    repo: "https://github.com/globocom/GloboDNS.git"
    dest: "{{ globodns_dstfolder }}"
  when: dep_installed is success
  register: deploy_sucess
...
