---
# tasks file for globodns
- name: clone GloboDNS repo
  git:
    repo: 'https://github.com/globocom/GloboDNS.git'
    dest: "{{ dstfolder }}"
  when: dep_installed|success
  register: deploy_sucess
...
