---
# tasks file for globodns
- name: "Configuring user {{ globodns_user }}"
  when: deploy_sucess is success
  user:
    state: present
    shell: /bin/bash
    name: "{{ globodns_user }}"
    groups: "globodns,{{ globodns_gidbind }}"
...
