---
# tasks file for globodns
- name: "Configurando usuário {{ user }}"
  when: deploy_sucess is success
  user:
    name: "{{ sysadmin }}"
    state: present
    shell: /bin/bash
    nome: "{{ dstfolder }}"
    groups: "globodns,{{ gidbind }}"
...
